name: CI
on:
  - push
#   - pull_request
jobs:
  test:
    env: 
      GKS_ENCODING: "utf8"
      GKSwstype: "nul"
    name: ${{ matrix.test_set }} - ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' || matrix.version == '^1.11.0-0' }}
    strategy:
      fail-fast: false
      matrix:
        test_set: ["basic", "plots", "higher_order", "estimation"]
        version: ['1.8', '1.9', '1.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]
        exclude:
          - version: '1.8'
            os: macOS-latest
          - version: '1.8'
            os: windows-latest
          - version: '1.9'
            os: macOS-latest
          - version: '1.9'
            os: windows-latest
        include:
          - os: ubuntu-latest
            prefix: xvfb-run
          - version: '1.10'
            os: ubuntu-latest
            arch: x64
            test_set: "1st_order_inversion_estimation"
          - version: '1.10'
            os: ubuntu-latest
            arch: x64
            test_set: "2nd_order_estimation"
          - version: '1.10'
            os: ubuntu-latest
            arch: x64
            test_set: "3rd_order_estimation"
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
            test_set: "basic"
            allow_failure: true
          - version: '^1.11.0-0'
            os: ubuntu-latest
            arch: x64
            test_set: "basic"
            allow_failure: true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}  
      - name: Set Custom Test Environment Variable
        if: matrix.os == 'windows-latest'
        run: echo "TEST_SET=${{ matrix.test_set }}" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
      - name: Set Custom Test Environment Variable (Unix)
        if: matrix.os != 'windows-latest'
        run: echo "TEST_SET=${{ matrix.test_set }}" >> $GITHUB_ENV
      - name: Set JULIA_NUM_THREADS for Julia 1.10 on Ubuntu
        if: matrix.version == '1.10' && matrix.os == 'ubuntu-latest' && (matrix.test_set == 'hmc_estimation' || matrix.test_set == 'tempering_estimation' || matrix.test_set == '2nd_order_estimation' || matrix.test_set == '3rd_order_estimation')
        run: echo "JULIA_NUM_THREADS=auto" >> $GITHUB_ENV
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: ${{ matrix.prefix }}  # for `xvfb-run`
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
